#Adapted from
#https://gist.github.com/NBTX/ebb0717e7d731a3b655c4c67b1708b3a#file-travis-yml
#https://gist.github.com/NBTX/e4150e3d552af482d08524408e51182c#file-travis-yml
os: linux

dist: trusty
jdk: oraclejdk8

language: node_js
node_js:
  - "12"

env:
  global:
    - ANDROID_SDK_ROOT=/opt/android

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
    packages:
      - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
      - libstdc++6
      - curl

cache:
  directories:
    - $HOME/.pub-cache
    - node_modules

before_script:
  - wget https://services.gradle.org/distributions/gradle-4.10.3-bin.zip
  - unzip -qq gradle-4.10.3-bin.zip
  - export GRADLE_HOME=`pwd`/gradle-4.10.3
  - export PATH=$GRADLE_HOME/bin:$PATH

  - mkdir -p /home/travis/.android
  - echo 'count=0' > /home/travis/.android/repositories.cfg

  - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - mkdir android-sdk-tools
  - unzip -qq sdk-tools-linux-4333796.zip -d android-sdk-tools
  - export PATH=`pwd`/android-sdk-tools/tools/bin:$PATH
  - mkdir -p $ANDROID_SDK_ROOT
  
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "tools" "build-tools;28.0.3" "extras;android;m2repository" > /dev/null
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH

  - sdkmanager --list

  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  
  - export PATH=$PATH:flutter/bin
  
script:
  - flutter precache
  - flutter analyze lib test
  - flutter format -n lib test
  - flutter test